services:
  apiwrapper:
    image: "drewl/ai-calendar-assistant:latest"
    ports:
    - "80:80"
    - "443:443"
    - "8989:8989"
    env_file:
      - .env
    environment:
      - OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - OPENAI_MODEL_DEPLOYMENT_NAME=${OPENAI_MODEL_DEPLOYMENT_NAME}
      - OPENAI_PROMPT=${OPENAI_PROMPT}=${OPENAI_PROMPT}
      - ENTRA_GRAPH_APPLICATION_CLIENT_ID=${ENTRA_GRAPH_APPLICATION_CLIENT_ID}
      - ENTRA_GRAPH_APPLICATION_CLIENT_SECRET=${ENTRA_GRAPH_APPLICATION_CLIENT_SECRET}
      - ENTRA_GRAPH_APPLICATION_TENANT_ID=${ENTRA_GRAPH_APPLICATION_TENANT_ID}
      - COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
      - COSMOS_KEY=${COSMOS_KEY}
      - COSMOS_DATABASE=${COSMOS_DATABASE}
      - COSMOS_CONTAINER=${COSMOS_CONTAINER}
      - CHAT_SESSION_ID=${CHAT_SESSION_ID}
      - GRAPH_DEBUG=${GRAPH_DEBUG}
      - TELEMETRY_CONSOLE_ENABLED=${TELEMETRY_CONSOLE_ENABLED}
      - TELEMETRY_CONSOLE_LEVEL=${TELEMETRY_CONSOLE_LEVEL}
      - TELEMETRY_CONSOLE_LEVEL_OPTIONS=${TELEMETRY_CONSOLE_LEVEL_OPTIONS}
      - TELEMETRY_CONSOLE_COLORS=${TELEMETRY_CONSOLE_COLORS}
      - TELEMETRY_CONSOLE_TIMESTAMP=${TELEMETRY_CONSOLE_TIMESTAMP}
      - TELEMETRY_CONSOLE_MODULE=${TELEMETRY_CONSOLE_MODULE}


