"""
CardPlugin — Semantic Kernel plugin that builds Adaptive Cards deterministically.

Registered on every specialist agent (Calendar, Directory, Location, Proxy).
Each kernel function wraps the corresponding builder in operations/card_operations.py
so card structure is always generated by code, never hallucinated by the LLM.
"""

import json
from typing import Annotated

from semantic_kernel.functions import kernel_function

from operations.card_operations import CardOperations

card_operations = CardOperations()


class CardPlugin:
    """
    Provides deterministic Adaptive Card construction as kernel functions.
    The LLM supplies structured data; this plugin produces the card JSON.
    """

    # ------------------------------------------------------------------ #
    #  Capabilities / demo card                                           #
    # ------------------------------------------------------------------ #

    @kernel_function(
        description="""
        Build a capabilities overview card that shows all platform features.

        CALL THIS WHEN the user says ANY of:
        - "show me your cards"
        - "show cards"
        - "demo"
        - "show capabilities"
        - "what can you do"
        - "help"

        No parameters required — the card content is fixed.

        Returns a JSON envelope:  {"message": "...", "cards": [...]}
        """
    )
    def build_capabilities_card(self) -> Annotated[str, "JSON envelope with message and cards array"]:
        cards = [
            {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.5",
                "body": [
                    {"type": "TextBlock", "text": "Calendar & Scheduling", "weight": "bolder", "size": "medium"},
                    {"type": "TextBlock", "text": "Schedule and cancel meetings, check availability, find conference rooms, create Teams/Zoom video calls.", "wrap": True, "spacing": "small"}
                ]
            },
            {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.5",
                "body": [
                    {"type": "TextBlock", "text": "People & Directory", "weight": "bolder", "size": "medium"},
                    {"type": "TextBlock", "text": "Search colleagues, view organisational charts, look up managers and contact details.", "wrap": True, "spacing": "small"}
                ]
            },
            {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.5",
                "body": [
                    {"type": "TextBlock", "text": "Location Search", "weight": "bolder", "size": "medium"},
                    {"type": "TextBlock", "text": "Find nearby restaurants, hotels, banks, coffee shops, and other amenities using Azure Maps.", "wrap": True, "spacing": "small"}
                ]
            },
            {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.5",
                "body": [
                    {"type": "TextBlock", "text": "Client Risk Analysis", "weight": "bolder", "size": "medium"},
                    {"type": "TextBlock", "text": "View client risk profiles, portfolio exposure, and compliance information.", "wrap": True, "spacing": "small"}
                ]
            },
        ]
        return json.dumps({"message": "Here are the platform capabilities", "cards": cards}, ensure_ascii=False)

    # ------------------------------------------------------------------ #
    #  Meeting created confirmation card                                  #
    # ------------------------------------------------------------------ #

    @kernel_function(
        description="""
        Build a meeting-confirmation card after a meeting has been successfully created.

        CALL THIS WHEN a meeting has just been created and you want to show a rich
        confirmation card to the user.

        The `meeting_json` parameter must be a JSON string with these fields
        (all optional but included where available):
          - subject       : meeting title
          - organizer     : organizer display name or email
          - attendees     : list of attendee objects (email_address.address or name)
          - location      : room / location string
          - start_time    : human-readable start (e.g. "Mon 9 Mar 10:00 AM")
          - end_time      : human-readable end
          - body          : agenda / meeting description text
          - id            : calendar event ID

        Returns a JSON envelope:  {"cards": [...]}
        """
    )
    def build_meeting_card(
        self,
        meeting_json: Annotated[str, "JSON object with meeting details (subject, organizer, attendees, location, start_time, end_time, body, id)"]
    ) -> Annotated[str, "JSON envelope with cards array"]:
        meeting = json.loads(meeting_json) if isinstance(meeting_json, str) else meeting_json
        card = card_operations.build_meeting_summary_card(meeting)
        return json.dumps({"cards": [card]}, ensure_ascii=False)

    # ------------------------------------------------------------------ #
    #  Scheduling conflict warning card                                   #
    # ------------------------------------------------------------------ #

    @kernel_function(
        description="""
        Build a scheduling-conflict warning card when one or more attendees
        have calendar conflicts with a proposed meeting time.

        CALL THIS WHEN conflict checking reveals busy attendees BEFORE creating
        the meeting, so the user can decide whether to proceed.

        Parameters:
          conflicts_json : JSON array of conflict objects, each with:
            - attendee_name      : display name of the busy attendee
            - conflicting_event  : title of their conflicting event
            - conflict_time      : time range string of the conflict

          meeting_json   : JSON object describing the proposed meeting with:
            - subject        : proposed meeting title
            - proposed_start : human-readable start time
            - proposed_end   : human-readable end time
            - organizer      : organizer name

        Returns a JSON envelope:  {"cards": [...]}
        """
    )
    def build_conflict_warning_card(
        self,
        conflicts_json: Annotated[str, "JSON array of conflict objects (attendee_name, conflicting_event, conflict_time)"],
        meeting_json: Annotated[str, "JSON object with proposed meeting details (subject, proposed_start, proposed_end, organizer)"]
    ) -> Annotated[str, "JSON envelope with cards array"]:
        conflicts = json.loads(conflicts_json) if isinstance(conflicts_json, str) else conflicts_json
        meeting = json.loads(meeting_json) if isinstance(meeting_json, str) else meeting_json
        card = card_operations.build_conflict_card(conflicts, meeting)
        return json.dumps({"cards": [card]}, ensure_ascii=False)

    # ------------------------------------------------------------------ #
    #  User profile card                                                  #
    # ------------------------------------------------------------------ #

    @kernel_function(
        description="""
        Build a user-profile card for displaying information about a person
        found in the Microsoft 365 directory.

        CALL THIS WHEN you have looked up a user (via the directory agent or
        graph plugin) and want to display their profile as a rich card.

        The `user_json` parameter must be a JSON string with these fields
        (all optional but included where available):
          - displayName    : full name
          - jobTitle       : job title
          - department     : department name
          - mail           : email address
          - mobilePhone    : mobile number
          - officeLocation : office / building

        Returns a JSON envelope:  {"cards": [...]}
        """
    )
    def build_profile_card(
        self,
        user_json: Annotated[str, "JSON object with user profile details (displayName, jobTitle, department, mail, mobilePhone, officeLocation)"]
    ) -> Annotated[str, "JSON envelope with cards array"]:
        user = json.loads(user_json) if isinstance(user_json, str) else user_json
        card = card_operations.build_user_profile_card(user)
        return json.dumps({"cards": [card]}, ensure_ascii=False)

    # ------------------------------------------------------------------ #
    #  Location search results card                                       #
    # ------------------------------------------------------------------ #

    @kernel_function(
        description="""
        Build a location-results card displaying nearby places found via
        Azure Maps (restaurants, hotels, coffee shops, banks, etc.).

        CALL THIS WHEN the location agent returns place results and you want
        to present them as a rich card.

        Parameters:
          results_json : JSON array of result objects, each with:
            - name     : place name
            - address  : formatted address string
            - rating   : rating string (e.g. "4.5") — optional
            - distance : distance string (e.g. "0.3 km") — optional

          query : the original search string the user typed (e.g. "coffee near Canary Wharf")

        Returns a JSON envelope:  {"cards": [...]}
        """
    )
    def build_location_card(
        self,
        results_json: Annotated[str, "JSON array of location results (name, address, rating, distance)"],
        query: Annotated[str, "Original search query from the user"]
    ) -> Annotated[str, "JSON envelope with cards array"]:
        results = json.loads(results_json) if isinstance(results_json, str) else results_json
        card = card_operations.build_location_results_card(results, query)
        return json.dumps({"cards": [card]}, ensure_ascii=False)

